###########################################
# Default YAML config file for snakemake.
# This file is loaded automatically at the top of the Snakefile.
#
# Additional configuration, can be specified to overwrite
# any the of the default settings like this:
# `snakemake all --configfile config/<run specific>.yaml`
#
###########################################




# Parameters related to AAV integration:
integration:
    # How many integration events:
    events: 10

    # How many allelles of the same integration event are
    # in the sample? E.g. if a cell with AAV integration has multiplied:
    expansion: 2

    # Size of AAV integration (drawn from a gamma distribution)
    # mean, stdev, min, min (optional)
    size: "1000,500,25"



# Parameters for preparing for read simulation:
read_sim:
    # length = mean, stdev on a gamma distribution, with an upper bound:
    # https://www.desmos.com/calculator/z2a3yqssie
    # mean,stdev,max
    length: "9000,3000,30000"

    # Simulated reads per event*expansion*amplification.
    # This parameter can be thought of as a post-enrichment amplification.
    # The parameter is passed to Badread:
    coverage: 10

    # Number of reads simulated from the genome
    # and submitted to target enrichment, then added
    # to the integration reads.
    # For 30x coverage: 30*3e9 / 9e3 = 1e7
    genome_reads: 10000000



# Parameters related to target enrichment:
enrichment:
    # Percent of reads that pass through
    # without enrichment:
    leakage: 1

    # Fold amplification, pre-enrichment:
    amplification: 10

    # Probability of pulling down a sequence.
    # This depeneds on a minimum length of complementarity (m)
    # and a parameter (q). The probability is defined by this function:
    # f(x) = 1 - 1 / (exp(q*(x-m))) if x>m else 0
    # q,m
    enrich_prob: "0.05,15"

    # Let the enrichment probability be additive with respect to multiple
    # binding sequences, found as supplementary alignments:
    additive: False



# Default settings passed on to badreads:
# https://github.com/rrwick/Badread?tab=readme-ov-file
badread:
    identity: "30,3"
    error_model: "pacbio2021"
    qscore_model: "pacbio2021"
    start_adapter: "100,100"
    end_adapter: "100,100"
    start_adapter_seq: 0
    end_adapter_seq: 0
    chimeras: 1
    glitches: "3000,1,1"

    # The junk and random reads should be set to 0
    # to avoid generating these with the large length distribution:
    junk_reads: 0
    random_reads: 0





