###########################################
## YAML config file
## Setup for full run on mimic.
## Default configuration, for example regarding coverage, statistics etc.
## is stored in "config.yaml" and loaded automatically in the Snakefile.
##
## To run this study, go to the base of the snakemake folder and run:
## `snakemake all --configfile config/testdata_config.yaml`
##
############################################




pipeline_dir: "."

# Organism reference genome:
genome_fnam: "test_ref.fa"

# AAV genome:
AAV_genome_fnam: "test_AAV.fa"

# Target enrichment panel:
# tes_panel_fnam: "~/bitbucket/davidkr2/development_AAV_integration/read_simulation/test_run/test_tes_panel.fa"
tes_panel_fnam: "test_AAV.fa"


workdir: "test_run"
# Specify run name, otherwise a new unique run name will be generated:
# run_name: "testrun"
adapters_fnam: False
keep_intermediate: False
threads: 15
repeats: 2




integration:
    # How many integration events:
    events: 10

    # How many allelles of the same integration event are
    # in the sample? E.g. if a cell with AAV integration has multiplied:
    expansion: 1

    # Size of AAV integration (drawn from a gamma distribution)
    # mean, stdev, min, min (optional)
    size: "200,50,25"


# Parameters for preparing for read simulation:
read_sim:
    # Number of reads simulated from the genome
    # and submitted to target enrichment, then added
    # to the integration reads.
    genome_reads: 100000






